## Write a Numpy program to compute the multiplication of two given matrixes

In [4]:
import numpy as np
arr1=np.array([[1,1],[2,2]])
arr2=np.array([[9,2],[1,1]])
arr=arr1*arr2

arr

array([[9, 2],
       [2, 2]])

## Write a NumPy program to compute the determinant of a given square array

In [7]:
import numpy as np

array=np .array([[2,2],
                 [3,2]])
arr2=np.linalg.det(array)
arr2

-2.0000000000000004

## Write a NumPy program to compute the cross product of two given vectors

In [9]:
import numpy as np

vec_1=np.array([1,2,3])
vec_2=np.array([2,2,2])
res_vec = vec_1 * vec_2
res_vec

array([2, 4, 6])

## Write a NumPy program to compute the condition number of a given matrix

## Write a NumPy program to compute the inverse of a given matrix

In [18]:
import numpy as np

arr1=np.array([[1,2,3],[2,4,9],[4,16,9]])
arr2=np.linalg.inv(arr1)
arr2

array([[ 4.5       , -1.25      , -0.25      ],
       [-0.75      ,  0.125     ,  0.125     ],
       [-0.66666667,  0.33333333, -0.        ]])